name: supabase_flutter
description: Flutter integration for Supabase. This package makes it simple for developers to build secure and scalable products.
version: 0.3.1+1
homepage: 'https://supabase.io'
repository: 'https://github.com/supabase/supabase-flutter'

environment:
  sdk: '>=2.14.0 <3.0.0'
  flutter: '>=2.5.0'

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  supabase: # Forked from 0.3.4
    git:
      url: git@github.com:DanMossa/supabase-dart.git
      ref: main
  uni_links: ^0.5.1
  url_launcher: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.2

flutter:
